"""Markdown report, shaped for pasting into a merge request or issue."""

from __future__ import annotations

from ..models import Confidence, Report
from .evidence import gap_before, select_display_lines

_BADGE = {
    Confidence.HIGH: "🔴",
    Confidence.MEDIUM: "🟡",
    Confidence.LOW: "⚪",
}


def render_markdown(report: Report, *, rule_limit: int = 5, evidence_limit: int = 60) -> str:
    job = report.job
    distilled = report.distilled
    stats = distilled.stats
    out: list[str] = []

    title = f"### pipelinemd — `{job.label}`"
    out.append(title)

    facts = []
    if job.project:
        facts.append(f"**project** `{job.project}`")
    if job.ref:
        facts.append(f"**ref** `{job.ref}`")
    if distilled.exit_code is not None:
        facts.append(f"**exit code** `{distilled.exit_code}`")
    if job.duration_s:
        facts.append(f"**duration** {job.duration_s:.0f}s")
    if facts:
        out += ["", " · ".join(facts)]
    if job.url:
        out += ["", f"[View job]({job.url})"]
    if distilled.failure_reason:
        out += ["", f"> {distilled.failure_reason}"]

    if diagnosis := report.diagnosis:
        badge = _BADGE[diagnosis.confidence]
        out += [
            "",
            f"#### {badge} {diagnosis.summary}",
            "",
            f"_{diagnosis.confidence.value} confidence · {diagnosis.category.value}_",
            "",
            diagnosis.root_cause,
        ]
        if diagnosis.fixes:
            out += ["", "**Suggested fixes**", ""]
            for index, fix in enumerate(diagnosis.fixes, start=1):
                out.append(f"{index}. **{fix.title}** — {fix.detail}")
                if fix.patch:
                    out += [
                        "",
                        "   ```",
                        *(f"   {line}" for line in fix.patch.splitlines()),
                        "   ```",
                    ]
            out.append("")
    elif top := report.top_hit:
        out += [
            "",
            f"#### {_BADGE[top.rule.confidence]} {top.rule.title}",
            "",
            f"_matched `{top.rule.id}` at line {top.line_number}_",
            "",
            top.rule.explanation,
            "",
            "**Try this**",
            "",
        ]
        out += [f"- {fix}" for fix in top.rule.fixes]

    if report.hits:
        out += ["", "<details><summary>Rule matches</summary>", ""]
        out += ["| rule | title | line | confidence |", "| --- | --- | --- | --- |"]
        for hit in report.hits[:rule_limit]:
            out.append(
                f"| `{hit.rule.id}` | {hit.rule.title} | {hit.line_number} "
                f"| {hit.rule.confidence.value} |"
            )
        out += ["", "</details>"]

    shown_lines, dropped = select_display_lines(distilled, evidence_limit)
    if shown_lines:
        shown = []
        previous = None
        for line in shown_lines:
            if gap := gap_before(previous, line):
                shown.append(f"... [{gap} lines omitted] ...")
            suffix = f"   [x{line.repeat}]" if line.collapsed else ""
            shown.append(f"{line.number:>6}  {line.text}{suffix}")
            previous = line
        if dropped:
            shown.append(f"... [{dropped} less relevant evidence lines hidden] ...")
        out += [
            "",
            f"<details><summary>Evidence — {stats.evidence_lines} of "
            f"{stats.raw_lines} lines ({stats.reduction:.1%} reduced)</summary>",
            "",
            "```log",
            *shown,
            "```",
            "",
            "</details>",
        ]

    out += ["", "<sub>Generated by [pipelinemd](https://github.com/rbalukja15/pipelinemd)"]
    if report.diagnosis and report.diagnosis.model:
        out[-1] += f" · diagnosis by `{report.diagnosis.model}`"
    out[-1] += "</sub>"
    return "\n".join(out) + "\n"
